site_name: OpenGov-Food Documentation
site_description: Comprehensive consumer protection and food safety inspection management system
site_author: Nik Jois
site_url: https://llamasearchai.github.io/OpenGov-Food

repo_name: llamasearchai/OpenGov-Food
repo_url: https://github.com/llamasearchai/OpenGov-Food
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 Nik Jois

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: table
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_bases: true
            show_categories: true
            show_docstring_attributes: true
            show_docstring_functions: true
            show_docstring_classes: true
            show_docstring_modules: true
            show_docstring_variables: true
            show_if_no_docstring: true
            show_inheritance_diagram: true
            show_labels: true
            show_object_full_path: true
            show_root_full_path: true
            show_root_heading: true
            show_root_toc_entry: true
            show_signature: true
            show_signature_annotations: true
            show_source: true
            show_submodules: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true

nav:
  - Home: index.md
  - Getting Started:
      - Installation: guides/installation.md
      - Quick Start: guides/quick-start.md
      - Configuration: guides/configuration.md
  - API Reference:
      - Overview: api/overview.md
      - Authentication: api/authentication.md
      - Items: api/items.md
      - Models: api/models.md
  - Architecture:
      - System Overview: architecture/overview.md
      - Database Design: architecture/database.md
      - Security: architecture/security.md
  - Development:
      - Contributing: development/contributing.md
      - Testing: development/testing.md
      - Deployment: development/deployment.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/llamasearchai/OpenGov-Food
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/nikjois

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference